### ISSUE TITLE
How to copy ejs template as raw file

### ISSUE THREAD

**Issue by zhangyuheng** [saojs/sao#101]
I got this error 

```
? What is the name of the project san
? How would you describe the project my polished project
Error: Could not find the include file "src/templates/header.ejs"
    at getIncludePath (/Users/-/create-app/node_modules/_ejs@2.6.1@ejs/lib/ejs.js:162:13)
    at includeSource (/Users/-/create-app/node_modules/_ejs@2.6.1@ejs/lib/ejs.js:306:17)
```

the html file is `create-app/template/src/entry/{page}/index.html`

```
<!DOCTYPE html>
<html>
  <head>
    <%- include src/templates/header.ejs -%>
  </head>
    <div id="app">
    </div>
  </body>
</html>

```

How to prevent compiling the ejs file.

**Comment by zhangyuheng** [comment]
[found it here](http://ejs.co/), use `<%%` => `<%- include src/templates/header.ejs -%>`
