### ISSUE TITLE
Error: Path contains invalid characters

### ISSUE THREAD

**Issue by zjxpcyc** [saojs/sao#63]
When i use ` sao github:zjxpcyc/dva-demo` in window 10 (x64), i got an error
```javascript
error Error: Path contains invalid characters: 
C:\Users\Administrator\.sao\repos\github:zjxpcyc::dva-demo\mock
    at checkPath (C:\Users\Administrator\AppData\Local\Yarn\config\global\node_modules\make-dir\index.js:18:16)
    at Promise.resolve.then (C:\Users\Administrator\AppData\Local\Yarn\config\global\node_modules\make-dir\index.js:26:2)
    at <anonymous>
```

Is a bug ?

**Comment by egoist** [comment]
um seems the path couldn't contain `:` on Windows..

**Comment by egoist** [comment]
Hi please try 0.22.3, it should be fixed.

btw there's no need to prefix `github:` if the repo is hosted on github.

**Comment by zjxpcyc** [comment]
thx, 0.22.3 fixed it !

**Comment by egoist** [comment]
@zjxpcyc glad to hear that 🍻
